version: "3.8"

services:
  airreport:
    build:
      context: .
    ports:
      - 3001:3001
    environment:
      - SERVER_PORT=3001
      - MYAIR_IP=192.168.0.30
      - MYAIR_PORT=2025
      - MYAIR_AIRCON=ac1
      - DB_CONNECTIONSTRING=mongodb://192.168.0.66:27017/AirconReports
      - DB_DATABASE=AirconReports
    volumes:
      - ./:/app
    command: npm run start
